### ISSUE TITLE
allowed MemorySize of 5120 is now 3008

### ISSUE THREAD

**Issue by cmuc24** [marknorrapscm/serverless-media-portal#10]
https://github.com/marknorrapscm/serverless-media-portal/blob/49dd663f25aaf769f7013cf7299230e44069d59a/backend/serverless.yml#L416

 Serverless Error ----------------------------------------
```
  An error occurred: ThumbnailMakerLambdaFunction - 
Resource handler returned message: 
'MemorySize' value failed to satisfy constraint: 
Member must have value less than or equal to 3008 
Service: Lambda, Status Code: 400
```

Setting to 3008, the deployment run without issues

**Comment by marknorrapscm** [comment]
Thanks for making this issue.

Is this the first Lambda you've created or the first Lambda you've created in this region? What region are you deploying to? I had never encountered this error and I know that Lambdas can have memory >3GB, but according to [this](https://stackoverflow.com/questions/70943739/aws-lambda-memorysize-value-failed-to-satisfy-constraint):

> Lambda functions with memory configuration greater than 3GB are currently unavailable for first time use in multiple regions. We are working on restoring this feature and mitigations are in progress. If you urgently require to use your function with memory greater than 3GB, please provide your account and region details so we can expedite access internally.

...the issue may be related to limits on your account. Can you confirm / deny?

If this is the issue, I may just lower the default RAM on that Lambda and write something in the docs to make people aware.
